import type { TopicNote } from "@/content/types";

export const unit1Notes: Record<string, TopicNote> = {
  "Data Communications": {
    selfTest: [
      "List the five components of a data communication system.",
      "What are the four fundamental characteristics that decide how effective a data communication system is?",
      "Name the three modes of data flow and give one real device for each.",
    ],
    body: `**Definition.** **Data communication** is the exchange of data between two devices through some form of transmission medium, such as a wire cable or radio waves. The word *data* means information presented in whatever form is agreed upon by the parties creating and using it. For data communication to happen, the communicating devices must be part of a communication system made of both hardware (physical equipment) and software (programs).

**Fundamental characteristics.** The effectiveness of a data communication system depends on four characteristics:

1. **Delivery.** The system must deliver data to the correct destination. Data must be received only by the intended device or user.
2. **Accuracy.** The system must deliver the data accurately. Data that has been altered in transmission and left uncorrected is unusable.
3. **Timeliness.** The system must deliver data in a timely manner. Late video or audio is useless, so real-time data must arrive in the same order and without significant delay.
4. **Jitter.** Jitter is the uneven delay in the arrival of packets. If video packets are sent every 30 ms but some arrive after 30 ms and others after 40 ms, the picture becomes uneven.

**Components.** A data communication system has five components:

1. **Message** – the information to be communicated (text, numbers, pictures, audio, video).
2. **Sender** – the device that sends the message (computer, phone, camera).
3. **Receiver** – the device that receives the message.
4. **Transmission medium** – the physical path the message travels on (twisted-pair cable, coaxial cable, fibre optic cable, radio waves).
5. **Protocol** – the set of rules that governs the communication. Without a protocol, two connected devices can exchange signals but cannot understand each other, just as a person speaking Nepali cannot be understood by someone who speaks only Japanese.

**Data representation.** Information today appears as text (Unicode/ASCII bit patterns), numbers (binary), images (a matrix of pixels, each a bit pattern, with RGB or YCM colour), audio (a continuous signal) and video (a sequence of images or a continuous signal).

**Data flow.** Communication between two devices can be:

| Mode | Direction | Example |
|---|---|---|
| Simplex | One way only; only one side can transmit | Keyboard to computer, traditional monitor, TV broadcast |
| Half-duplex | Both directions, but not at the same time | Walkie-talkie, CB radio |
| Full-duplex | Both directions at the same time | Telephone call, mobile phone |

**Example.** When a student sends an email from a laptop in Kathmandu to a friend in Biratnagar: the email text is the *message*, the laptop is the *sender*, the friend's phone is the *receiver*, the Wi-Fi, copper and fibre links form the *medium*, and SMTP, TCP and IP are the *protocols*.

**How it's asked in exams.** *"What is data communication? Explain its components and characteristics"* (6–8 marks), or *"Explain the different modes of data flow"* (4 marks). Define data communication, explain all four characteristics and all five components in full sentences, draw the diagram showing sender → medium → receiver with the protocol (rules) box on both sides and the message travelling along the medium, add the data flow table, and finish with a sentence saying that all five components must be present and all four characteristics met for communication to be effective.`,
  },

  "Networks": {
    selfTest: [
      "How many duplex links are needed to fully connect 6 devices in a mesh topology?",
      "Name the three criteria used to judge a network.",
      "Differentiate between a LAN and a WAN in one line each.",
    ],
    body: `**Definition.** A **network** is a set of devices (called *nodes*) connected by communication links. A node can be a computer, printer, or any other device capable of sending or receiving data generated by other nodes on the network. A link can be a cable or a wireless channel.

**Network criteria.** A network must meet three criteria:

- **Performance** – measured by transit time and response time. It depends on the number of users, the type of medium, the hardware and the software. It is usually judged by two metrics: **throughput** (more is better) and **delay** (less is better).
- **Reliability** – measured by how often failures happen, the time the network takes to recover from a failure, and its robustness in a catastrophe.
- **Security** – protecting data from unauthorized access, protecting data from damage, and having procedures to recover from breaches and data losses.

**Type of connection.** A **point-to-point** connection is a dedicated link between exactly two devices (for example, a TV and its remote control). A **multipoint** (multidrop) connection is one in which more than two devices share a single link, either at the same time (spatially shared) or by taking turns (time shared).

**Physical topologies.**

| Topology | Structure | Advantages | Disadvantages |
|---|---|---|---|
| Mesh | Every device has a dedicated link to every other device; n(n−1)/2 duplex links, each device needs n−1 ports | Robust, no traffic sharing, privacy, easy fault identification | Much cabling and many I/O ports, expensive |
| Star | Every device connects to a central hub or switch | Cheap, easy to install, one link failure affects only one device | Whole network fails if the hub fails |
| Bus | All devices tap into one long backbone cable | Least cabling, easy installation | A break in the backbone stops all traffic; hard to add devices; signal reflections |
| Ring | Each device connects to its two neighbours; the signal passes around the loop through repeaters | Easy to install and reconfigure, fault isolation is simple | A break in the ring can disable the whole network (unless a dual ring is used) |

A **hybrid** topology combines these, for example a star backbone with bus branches.

**Categories of networks.**

- **LAN (Local Area Network)** – privately owned, covers a single office, building or campus (up to a few kilometres). Example: the computer lab of a college using Ethernet switches.
- **MAN (Metropolitan Area Network)** – covers a town or city. Example: a cable TV network or an ISP's fibre ring across Kathmandu Valley.
- **WAN (Wide Area Network)** – covers a large geographic area such as a country, a continent or the whole world. A *switched WAN* connects end systems through routers (for example, the Internet backbone); a *point-to-point WAN* is a single line leased from a telephone company.

**Example.** For 6 devices in a mesh: links = 6 × 5 / 2 = **15 duplex links**, and each device needs **5 I/O ports**. The same 6 devices in a star need only 6 links and one port each, which is why star is the most common LAN topology.

**How it's asked in exams.** *"What is a network topology? Explain the different topologies with their advantages and disadvantages"* (8–12 marks), or *"Differentiate between LAN, MAN and WAN"* (4–6 marks). Define network and topology, draw the diagram showing each topology (mesh, star, bus, ring) with 4–5 nodes, explain each with advantages and disadvantages in full sentences, include the mesh link formula with a small calculation, and conclude that star is the most widely used LAN topology because of its low cost and easy fault isolation.`,
  },

  "The Internet": {
    selfTest: [
      "What was the name of the network (and its year) from which the Internet grew?",
      "What is an ISP? Name the levels in the ISP hierarchy.",
      "Differentiate between the internet (small i) and the Internet (capital I).",
    ],
    body: `**Definition.** An **internet** (small i) is two or more networks connected so that they can communicate with each other; this is also called an *internetwork*. **The Internet** (capital I) is the best-known internet: a worldwide collaboration of hundreds of thousands of interconnected networks that all use the **TCP/IP protocol suite**. It is used by private individuals, businesses, governments and universities.

**Brief history.**

- In the mid-1960s, research computers from different makers could not communicate. The Advanced Research Projects Agency (**ARPA**) of the US Department of Defense wanted to connect them.
- In **1969**, **ARPANET** became a reality, connecting four nodes: UCLA, UCSB, Stanford Research Institute (SRI) and the University of Utah, using special computers called *Interface Message Processors* (IMPs).
- In **1972–1974**, Vint Cerf and Bob Kahn developed the *Internetting Project* and the idea of gateways; TCP was later split into **TCP and IP**. In 1983 ARPANET switched fully to TCP/IP.
- ARPANET later split into MILNET (military) and ARPANET (non-military). CSNET (1981) and **NSFNET** (1986) extended the network to universities.
- In the 1990s commercial ISPs took over, the World Wide Web (Tim Berners-Lee, CERN) appeared, and the Internet grew to its present size.

**The Internet today.** The Internet is not a single network but a structure of backbones, provider networks and customer networks, organized in a hierarchy of **Internet Service Providers (ISPs)**:

1. **International ISPs** – connect nations together at the top of the hierarchy.
2. **National ISPs** – backbone networks maintained by large companies; they are connected to one another by complex switching stations called **Network Access Points (NAPs)** or peering points.
3. **Regional ISPs** – smaller ISPs connected to one or more national ISPs.
4. **Local ISPs** – provide direct service to end users; they may be companies, universities or non-profit organizations connected to regional or national ISPs.

**Example.** A home user in Lalitpur connects to a local ISP such as Worldlink or Nepal Telecom. That ISP connects through international links (via India, and satellite or fibre routes) to large international carriers, and a request to a web server in the USA passes through several ISPs of different levels before reaching the server. The user's browser, the ISP's routers and the web server all speak TCP/IP.

**How it's asked in exams.** *"What is the Internet? Explain its history and present-day structure"* (6–8 marks), or a short note on *"Internet / ISP"* (4 marks). Give the definition, the key historical milestones with years (ARPANET 1969, TCP/IP 1983, NSFNET 1986), draw the diagram showing the hierarchy of international, national, regional and local ISPs with end users at the bottom and NAPs linking national ISPs, and conclude that the Internet is a network of networks held together by the common TCP/IP protocol suite.`,
  },

  "Protocols and Standards": {
    selfTest: [
      "What are the three key elements of a protocol?",
      "Differentiate between de facto and de jure standards.",
      "Name any three standards organizations and one standard each has produced.",
    ],
    body: `**Definition.** A **protocol** is a set of rules that governs data communication. It defines *what* is communicated, *how* it is communicated and *when* it is communicated. A **standard** is an agreed-upon rule or specification that manufacturers, vendors, government agencies and service providers follow, so that products from different companies can work together (interoperability).

**Key elements of a protocol.**

1. **Syntax** – the structure or format of the data, meaning the order in which the fields are presented. For example, a simple protocol might expect the first 8 bits to be the sender's address, the next 8 bits the receiver's address, and the rest the message.
2. **Semantics** – the meaning of each section of bits. It answers how a particular pattern is to be interpreted and what action is taken based on it. For example, does an address field identify the route to be taken or the final destination?
3. **Timing** – when data should be sent and how fast. If a sender produces data at 100 Mbps but the receiver can process only 1 Mbps, the receiver is overloaded and data is lost.

**Categories of standards.**

| Basis | De facto standard | De jure standard |
|---|---|---|
| Meaning | "By fact" or "by convention" | "By law" or "by regulation" |
| How created | Adopted through widespread use, not approved by any official body | Legislated by an officially recognized standards body |
| Example | Early TCP/IP use, Microsoft's early PC formats | OSI model (ISO), V-series modems (ITU-T), IEEE 802.3 |

**Standards organizations.**

- **ISO** (International Organization for Standardization) – multinational body; produced the **OSI model**.
- **ITU-T** (International Telecommunication Union – Telecommunication Standards Sector, formerly CCITT) – telecommunication standards such as V.90 modems and X.25.
- **ANSI** (American National Standards Institute) – US private non-profit; produced SONET standards.
- **IEEE** (Institute of Electrical and Electronics Engineers) – the IEEE 802 LAN standards, e.g. 802.3 Ethernet and 802.11 Wi-Fi.
- **EIA** (Electronic Industries Association) – interface standards such as EIA-232 (RS-232).

**Internet standards.** An Internet standard is a thoroughly tested specification. It starts as an **Internet draft** (a working document valid for six months), and may then be published as a **Request for Comment (RFC)**. An RFC moves through maturity levels: *proposed standard → draft standard → Internet standard*, while others are classified as *historic, experimental* or *informational*. Internet administration is handled by **ISOC** (Internet Society), **IAB** (Internet Architecture Board), **IETF** (Internet Engineering Task Force) and **IRTF** (Internet Research Task Force).

**Example.** HTTP is a protocol: its *syntax* is the request line "GET /index.html HTTP/1.1" followed by headers; its *semantics* say that GET means "send me this resource" and status 404 means "not found"; its *timing* rules decide when the client may send the next request. HTTP itself is published as an RFC by the IETF.

**How it's asked in exams.** *"What is a protocol? Explain its key elements. Why are standards needed?"* (6–8 marks). Define protocol and standard, explain syntax, semantics and timing each with an example, give the de facto versus de jure table, list at least four standards organizations with what they standardized, and conclude that standards guarantee interoperability and a larger, cheaper market for networking products.`,
  },

  "Layered Tasks": {
    selfTest: [
      "In the letter-sending analogy, what are the three layers at the sender side?",
      "Why is communication divided into layers instead of being handled as one task?",
      "In what order are the tasks performed at the receiver compared with the sender?",
    ],
    body: `**Definition.** **Layered tasks** means dividing the complex job of communication into a hierarchy of smaller, separate tasks (layers). Each layer performs a specific set of functions, uses the services of the layer immediately below it, and provides services to the layer immediately above it.

**Explanation with the letter-sending analogy (Forouzan).** Consider sending a letter to a friend in another city. The process involves a sender, a receiver and a carrier that transports the letter, and the tasks are arranged in layers:

**At the sender site:**

1. **Higher layer** – the sender writes the letter, inserts it into an envelope, writes the sender and receiver addresses, and drops it in a mailbox.
2. **Middle layer** – the letter is picked up by a letter carrier and delivered to the post office.
3. **Lower layer** – the letter is sorted at the post office and a carrier transports it towards the destination.

**On the way:** the letter is carried by truck, train, aeroplane or boat, possibly passing through several post offices.

**At the receiver site (tasks in reverse order):**

1. **Lower layer** – the carrier transports the letter to the destination post office.
2. **Middle layer** – the letter is sorted and delivered to the recipient's mailbox.
3. **Higher layer** – the receiver picks up the letter, opens the envelope and reads it.

**Key ideas shown by the analogy.**

- **Hierarchy.** Tasks must be done in order: the letter must be written and addressed before it can be picked up, and it must be delivered before it can be read.
- **Services.** Each layer uses the services of the layer below it. The writer does not need to know how trucks or aeroplanes work; they only need a mailbox.
- **Peer relationship.** The sender's higher layer and the receiver's higher layer deal with the same object (the opened letter), so layers at the same level on both sides are called *peers*.
- **Reverse order.** Tasks at the receiver are carried out in the reverse order of the sender.

**Advantages of layering.** It breaks a complex problem into manageable parts, allows each layer to be designed and changed independently (for example, replacing copper with fibre does not change email software), makes troubleshooting easier, and allows standard interfaces so that products from different vendors can work together.

**Example.** In a real network, the web browser (upper layer) creates a request, TCP (middle) divides it into segments and ensures reliable delivery, and the Ethernet card and cable (lower layers) carry the bits. Replacing Wi-Fi with an Ethernet cable changes only the lowest layer.

**How it's asked in exams.** *"Explain the concept of layered tasks with a suitable example"* or *"Why is a layered architecture used in networking?"* (4–6 marks). Explain the definition, draw the diagram showing sender, carrier and receiver with three layers on each side (higher, middle, lower) and the letter going down at the sender and up at the receiver, list the key ideas (hierarchy, services, peers, reverse order), give the advantages, and conclude that this layered idea is the basis of the OSI and TCP/IP models.`,
  },

  "OSI Model": {
    selfTest: [
      "Name the seven layers of the OSI model from bottom to top.",
      "Which layer is responsible for process-to-process delivery, and which for host-to-host (source-to-destination) delivery?",
      "Which layer adds both a header and a trailer to the data?",
    ],
    body: `**Definition.** The **Open Systems Interconnection (OSI) model** is a seven-layer reference model developed by the **International Organization for Standardization (ISO)** and first introduced in the late 1970s. An *open system* is a set of protocols that allows any two different systems to communicate regardless of their underlying architecture. The OSI model is not a protocol; it is a framework for understanding and designing network architecture that is flexible, robust and interoperable.

**Layered architecture.** The model has seven separate but related layers. As a message travels from device A to device B, it goes down through the layers at A, travels over the physical medium, and goes up through the layers at B. Layers at the same level on the two machines communicate as **peer-to-peer processes** using their protocol, while adjacent layers on the same machine communicate through **interfaces**. At each sending layer a **header** is added (the data link layer also adds a **trailer**); this is called **encapsulation**. At the receiver each layer removes its own header (decapsulation).

**Functions of each layer (top to bottom).**

1. **Application layer (7)** – enables the user (human or software) to access the network. It provides user interfaces and services such as network virtual terminal, file transfer, access and management (FTAM), mail services and directory services.
2. **Presentation layer (6)** – concerned with the syntax and semantics of the information exchanged: **translation** (different encoding systems), **encryption/decryption** for privacy, and **compression** to reduce the number of bits.
3. **Session layer (5)** – the network *dialog controller*. It establishes, maintains and synchronizes interaction: **dialog control** (half- or full-duplex) and **synchronization** (adding checkpoints so that a failed transfer of a 2000-page file resumes from the last checkpoint).
4. **Transport layer (4)** – **process-to-process delivery** of the entire message. Functions: service-point (port) addressing, segmentation and reassembly with sequence numbers, connection control, end-to-end flow control and end-to-end error control.
5. **Network layer (3)** – **source-to-destination (host-to-host) delivery** of packets, possibly across multiple networks. Functions: **logical addressing** (IP address) and **routing**.
6. **Data link layer (2)** – **hop-to-hop (node-to-node) delivery**. It turns the raw physical layer into a reliable link. Functions: framing, physical addressing (MAC address), flow control, error control (trailer) and access control on shared links.
7. **Physical layer (1)** – moves individual **bits** over the medium. It defines interface and medium characteristics, representation of bits (encoding), data rate, synchronization of bits, line configuration (point-to-point or multipoint), physical topology and transmission mode (simplex, half- or full-duplex).

**Summary table.**

| Layer | Data unit | Key responsibility | Example protocol / device |
|---|---|---|---|
| 7 Application | Message / data | Network services to user | HTTP, FTP, SMTP, DNS |
| 6 Presentation | Data | Translation, encryption, compression | JPEG, MPEG, SSL/TLS, ASCII |
| 5 Session | Data | Dialog control, synchronization | RPC, NetBIOS |
| 4 Transport | Segment | Process-to-process delivery | TCP, UDP (port numbers) |
| 3 Network | Packet / datagram | Host-to-host delivery, routing | IP, ICMP; router |
| 2 Data link | Frame | Hop-to-hop delivery, framing, MAC | Ethernet, PPP, HDLC; switch, bridge |
| 1 Physical | Bits | Transmission of raw bits | RJ-45, fibre, RS-232; hub, repeater |

A common memory aid from layer 7 to 1: *All People Seem To Need Data Processing.*

**Example.** When a student opens a website: the browser uses HTTP (application), the page may be encrypted with TLS (presentation), a session is kept open (session), TCP delivers it to port 443 (transport), IP routes it across routers (network), Ethernet or Wi-Fi frames carry it hop by hop (data link), and electrical or radio signals carry the bits (physical).

**How it's asked in exams.** One of the most repeated questions: *"Explain the OSI reference model with the functions of each layer"* (8–12 marks). Define the model and who developed it, draw the diagram showing the seven layers on two devices with peer-to-peer arrows between matching layers, headers H7 to H2 being added on the way down and trailer T2 at the data link layer, then explain each layer's functions in its own paragraph with an example protocol. Add the summary table, and conclude that although OSI is rarely implemented directly, it remains the standard reference for understanding and teaching networks.`,
  },

  "TCP/IP Protocol Architecture": {
    selfTest: [
      "Name the layers of the TCP/IP protocol suite and state how they map to the OSI model.",
      "Which transport-layer protocols are defined in TCP/IP?",
      "Name the four levels of addresses used in a TCP/IP internet.",
    ],
    body: `**Definition.** The **TCP/IP protocol suite** is the set of protocols on which the Internet is built. It was developed before the OSI model, as part of ARPANET research, so its layers do not match OSI exactly. The original TCP/IP model has **four layers**: host-to-network, internet, transport and application. Forouzan describes it as **five layers**: physical, data link, network, transport and application, where the lowest two correspond to the original host-to-network layer. TCP/IP is a **hierarchical** protocol made of interactive modules, each providing a specific function, but the modules are not necessarily interdependent.

**Layers and protocols.**

1. **Physical and data link layers** – TCP/IP does not define any specific protocol here; it supports all the standard and proprietary protocols (Ethernet, Wi-Fi, PPP, and so on). A network in a TCP/IP internet can be a LAN or a WAN.
2. **Network (internet) layer** – TCP/IP supports the **Internetworking Protocol (IP)**, an unreliable, connectionless, best-effort protocol that sends packets called **datagrams**, each travelling independently. It uses four supporting protocols:
   - **ARP** (Address Resolution Protocol) – finds the physical address from a known IP address.
   - **RARP** (Reverse ARP) – finds the IP address from a known physical address.
   - **ICMP** (Internet Control Message Protocol) – sends error and query messages back to the sender (used by ping).
   - **IGMP** (Internet Group Message Protocol) – supports multicasting.
3. **Transport layer** – process-to-process delivery using:
   - **TCP** (Transmission Control Protocol) – reliable, connection-oriented, stream-based; divides the stream into segments with sequence numbers.
   - **UDP** (User Datagram Protocol) – simple, connectionless, unreliable; adds only port addresses, checksum and length.
   - **SCTP** (Stream Control Transmission Protocol) – newer protocol for applications such as voice over the Internet, combining features of UDP and TCP.
4. **Application layer** – equivalent to the combined session, presentation and application layers of OSI. Protocols include **HTTP, SMTP, FTP, TELNET, DNS, SNMP**.

**Addressing in TCP/IP.** Four levels of addresses are used: **physical (link) address** (e.g. 48-bit Ethernet MAC 07:01:02:01:2C:4B), **logical (IP) address** (32-bit IPv4), **port address** (16-bit, e.g. 80 for HTTP) and **specific address** (user-friendly, e.g. an email address or URL).

**OSI versus TCP/IP.**

| Basis | OSI model | TCP/IP model |
|---|---|---|
| Developed by | ISO (a standards body) | US Department of Defense / ARPANET researchers |
| Number of layers | 7 | 4 (original) or 5 (Forouzan) |
| Nature | Reference model developed before the protocols | Protocols came first; model describes them |
| Session and presentation | Separate layers | Merged into the application layer |
| Transport layer | Connection-oriented and connectionless defined | TCP (connection-oriented), UDP and SCTP |
| Network layer | Connection-oriented and connectionless | Connectionless only (IP) |
| Distinction of service, interface, protocol | Clearly defined | Not clearly separated |
| Usage | Mainly a theoretical/teaching reference | Practical standard used by the Internet |

**Example.** Sending an email: SMTP (application) passes the message to TCP (transport, port 25), which passes segments to IP (network), which uses ARP to find the next router's MAC address and hands the datagram to Ethernet (data link), which sends bits over the cable (physical).

**How it's asked in exams.** *"Explain the TCP/IP protocol suite"* (8 marks) or, very commonly, *"Compare the OSI model with the TCP/IP model"* (8–12 marks). Define TCP/IP, draw the diagram showing TCP/IP layers side by side with the OSI layers (application of TCP/IP covering OSI layers 5–7, and the protocols IP, ARP, RARP, ICMP, IGMP, TCP, UDP, SCTP, HTTP, SMTP, FTP placed in their layers), explain each layer and its protocols, add the comparison table with at least six points, and conclude that TCP/IP is the practical standard of the Internet while OSI remains the conceptual reference.`,
  },
};
