import type { SubjectContent } from "@/content/types";
import { unit1Notes } from "./notes/unit-1";
import { unit2Notes } from "./notes/unit-2";
import { unit3Notes } from "./notes/unit-3";
import { unit4Notes } from "./notes/unit-4";
import { unit5Notes } from "./notes/unit-5";
import { unit6Notes } from "./notes/unit-6";
import { unit7Notes } from "./notes/unit-7";

export const dcnContent: SubjectContent = {
  flashcards: [
    // Unit 1: Overview of Data Communication and Networking
    {
      id: "fc-1",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is Data Communication?",
      back: "Data Communication is the exchange of data (in the form of 0s and 1s) between two devices via some form of transmission medium, requiring the sender, receiver, message, medium, and a mutually agreed protocol to be delivered correctly.",
    },
    {
      id: "fc-2",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What are the four fundamental characteristics of an effective data communication system?",
      back: "Delivery (data must reach the correct intended device/user), Accuracy (data must be delivered without alteration or corruption), Timeliness (data must arrive within a reasonable/required time, especially for audio/video), and Jitter (variation in packet arrival time must be kept low, or it degrades real-time data quality).",
    },
    {
      id: "fc-3",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is a Network, and what is Network Criteria?",
      back: "A Network is a set of interconnected devices (nodes) capable of exchanging data with each other. Network criteria are the properties used to judge a network's quality: Performance (throughput and delay), Reliability (measured by frequency of failure/recovery time), and Security (protecting data from unauthorized access or damage).",
    },
    {
      id: "fc-4",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "Distinguish between Point-to-Point and Multipoint physical topology/connections.",
      back: "A Point-to-Point connection provides a dedicated link between exactly two devices, using the entire link's capacity for just that pair. A Multipoint (multidrop) connection is a link shared among more than two devices simultaneously or by taking turns.",
    },
    {
      id: "fc-5",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "Name and briefly describe the four basic network topologies.",
      back: "Mesh: every device has a dedicated point-to-point link to every other device. Star: every device connects to one central hub/switch. Bus: all devices share a single common backbone cable. Ring: each device connects to exactly two neighboring devices, forming a closed loop.",
    },
    {
      id: "fc-6",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is the Internet?",
      back: "The Internet is a global network of interconnected networks (an 'internetwork') that uses the TCP/IP protocol suite to allow billions of devices worldwide to communicate, built up from LANs and WANs connected by routers and ISPs.",
    },
    {
      id: "fc-7",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is a Protocol, and what are its three key elements?",
      back: "A Protocol is a set of rules that governs data communication between devices. Its three key elements are Syntax (the structure/format of the data, i.e. the order in which bits/fields appear), Semantics (the meaning of each section of bits, i.e. how a pattern is to be interpreted and what action to take), and Timing (when data should be sent and how fast, i.e. rate matching between sender and receiver).",
    },
    {
      id: "fc-8",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is a Standard, and what is the difference between de facto and de jure standards?",
      back: "A Standard is an agreed-upon set of rules that data communication products must follow to ensure interoperability between products from different vendors. A de facto standard emerges from widespread industry adoption without formal ratification, while a de jure standard is one legislated/ratified by an official recognized body (e.g. ISO, ITU-T).",
    },
    {
      id: "fc-9",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "Why are protocols organized as a Layered Task, and what is the OSI Model?",
      back: "Layering breaks the complex task of network communication into smaller, independent, manageable sub-tasks, where each layer only needs to know how to interact with the layers directly above and below it. The OSI (Open Systems Interconnection) Model is a 7-layer conceptual reference model (Physical, Data Link, Network, Transport, Session, Presentation, Application) describing how this should be structured.",
    },
    {
      id: "fc-10",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "hedge",
      front: "Briefly, what is the role of each OSI layer?",
      back: "Physical: transmits raw bits over a medium. Data Link: organizes bits into frames, handles node-to-node delivery and error detection. Network: handles routing/logical addressing (source to destination). Transport: ensures process-to-process delivery of the entire message. Session: establishes/manages/synchronizes dialog between applications. Presentation: handles translation, encryption, compression of data. Application: provides services directly to the end user (e.g. email, file transfer).",
    },
    {
      id: "fc-11",
      unit: "Unit 1: Overview of Data Communication and Networking",
      tier: "core",
      front: "What is the TCP/IP Protocol Architecture, and how does it compare to OSI?",
      back: "TCP/IP is a practical, widely-implemented 4 or 5-layer protocol suite (Network Interface/Physical+Data Link, Internet/Network, Transport, Application) that the real-world Internet actually runs on. Unlike OSI's separate Session/Presentation/Application layers, TCP/IP combines all of that functionality into a single Application layer.",
    },

    // Unit 2: Physical Layer
    {
      id: "fc-12",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "Distinguish between Analog and Digital signals.",
      back: "An Analog signal is a continuous waveform that can take on an infinite number of values over a range of time (e.g. human voice, a sine wave). A Digital signal is a discrete waveform that can take on only a limited, finite number of values (typically two: 0 and 1), making it easier to regenerate cleanly and resist noise.",
    },
    {
      id: "fc-13",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "What is the Data Rate Limit, and what do the Nyquist and Shannon formulas tell us?",
      back: "The Data Rate Limit is the theoretical maximum speed at which data can be transmitted over a given channel. The Nyquist formula (for a noiseless channel) gives the maximum bit rate as a function of bandwidth and signal levels. The Shannon Capacity formula (for a noisy channel) gives the maximum bit rate as a function of bandwidth and the Signal-to-Noise Ratio (SNR).",
    },
    {
      id: "fc-14",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "Name the three main types of Transmission Impairment.",
      back: "Attenuation: the signal loses strength/energy as it travels a longer distance, requiring amplifiers to boost it. Distortion: the signal's shape changes because different frequency components travel at different speeds through the medium. Noise: unwanted random energy (thermal, induced, crosstalk, impulse) is added to the signal, corrupting it.",
    },
    {
      id: "fc-15",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is Line Coding, and what is Block Coding?",
      back: "Line Coding is the process of converting a stream of binary data (0s and 1s) into a digital signal suitable for physical transmission (e.g. NRZ, Manchester encoding). Block Coding adds extra redundant bits to a block of data before line coding, to help the receiver detect (or correct) transmission errors and maintain synchronization.",
    },
    {
      id: "fc-16",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is Sampling, in the context of converting analog data to digital?",
      back: "Sampling is the process of measuring the amplitude of an analog signal at regular, fixed time intervals to obtain a set of discrete values (samples), which are then quantized and encoded into a digital bit stream (e.g. Pulse Code Modulation, PCM). The Nyquist sampling theorem states the sampling rate must be at least twice the highest frequency in the signal to reconstruct it accurately.",
    },
    {
      id: "fc-17",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "What are the three Transmission Modes for sending bits over a link?",
      back: "Simplex: data flows in only one direction, never back (e.g. a keyboard to CPU). Half-Duplex: data flows in both directions, but only one direction at a time (e.g. a walkie-talkie). Full-Duplex: data flows in both directions simultaneously (e.g. a telephone call).",
    },
    {
      id: "fc-18",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is Modulation of Digital Data (Digital-to-Analog conversion)?",
      back: "Modulation of digital data converts a digital bit stream into an analog signal for transmission over an analog medium, by varying one property of a carrier wave. The three basic techniques are Amplitude Shift Keying (ASK), Frequency Shift Keying (FSK), and Phase Shift Keying (PSK).",
    },
    {
      id: "fc-19",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is Modulation of Analog Signal (Analog-to-Analog conversion)?",
      back: "Modulation of an analog signal (e.g. voice) onto a carrier wave for transmission (e.g. over radio) is done via Amplitude Modulation (AM, varying the carrier's amplitude), Frequency Modulation (FM, varying the carrier's frequency), or Phase Modulation (PM, varying the carrier's phase).",
    },
    {
      id: "fc-20",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "What is Multiplexing, and name the three common types (FDM, WDM, TDM)?",
      back: "Multiplexing combines multiple signals from different sources so they can share one physical transmission medium efficiently. FDM (Frequency Division Multiplexing): each signal is assigned its own separate frequency band. WDM (Wavelength Division Multiplexing): used for fiber optics, each signal is assigned its own light wavelength. TDM (Time Division Multiplexing): each signal is assigned its own recurring time slot on the shared link.",
    },
    {
      id: "fc-21",
      unit: "Unit 2: Physical Layer",
      tier: "core",
      front: "Distinguish between Guided Media and Unguided Media.",
      back: "Guided Media (wired) physically confines the signal within a solid medium, such as Twisted-Pair Cable, Coaxial Cable, or Fiber-Optic Cable. Unguided Media (wireless) transmits electromagnetic waves through free space/air without a physical conductor, such as radio waves, microwaves, and infrared.",
    },
    {
      id: "fc-22",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is Circuit Switching, and how do Telephone Networks use it?",
      back: "Circuit Switching establishes a single dedicated, fixed physical path (circuit) between sender and receiver for the entire duration of a communication session, before any data is sent. Traditional Telephone Networks use circuit switching, reserving a fixed line/bandwidth for a call from setup until it is torn down, regardless of whether data is actively flowing.",
    },
    {
      id: "fc-23",
      unit: "Unit 2: Physical Layer",
      tier: "hedge",
      front: "What is DSL Technology, Cable Modem, and SONET?",
      back: "DSL (Digital Subscriber Line) provides high-speed digital data transmission over existing copper telephone lines. A Cable Modem provides Internet access over the existing coaxial cable TV infrastructure. SONET (Synchronous Optical Network) is a high-speed standard for transmitting large volumes of digital data over fiber-optic cable, commonly used for long-haul backbone networks.",
    },

    // Unit 3: Data Link Layer
    {
      id: "fc-24",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What are the two types of Transmission Errors?",
      back: "A Single-bit error occurs when only one bit in a data unit is altered (changed from 0 to 1 or vice versa) during transmission. A Burst error occurs when two or more bits in a data unit are altered, with the errors not necessarily contiguous but all occurring between the first and last corrupted bit.",
    },
    {
      id: "fc-25",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What is Error Detection, and name a common technique.",
      back: "Error Detection is the process of checking whether any error has occurred during transmission, without necessarily identifying which bit(s) are wrong. A common technique is CRC (Cyclic Redundancy Check), where the sender appends a computed remainder (checksum) to the data, and the receiver recomputes it to check for a mismatch.",
    },
    {
      id: "fc-26",
      unit: "Unit 3: Data Link Layer",
      tier: "hedge",
      front: "What is Error Correction, and what is Hamming Code used for?",
      back: "Error Correction goes further than detection — it allows the receiver to identify exactly which bit(s) are wrong and fix them without retransmission. Hamming Code is a widely-used error-correcting code that adds redundant parity bits at specific positions, enabling single-bit errors to be both detected and automatically corrected.",
    },
    {
      id: "fc-27",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What is Flow Control?",
      back: "Flow Control is a technique that ensures a fast sender does not overwhelm a slower receiver with data faster than it can process/buffer it, using mechanisms like a sliding window so the receiver can signal how much more data it is ready to accept.",
    },
    {
      id: "fc-28",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "Describe Stop-and-Wait ARQ.",
      back: "In Stop-and-Wait ARQ (Automatic Repeat reQuest), the sender transmits exactly one frame and then stops, waiting for an acknowledgment (ACK) from the receiver before sending the next frame. If no ACK arrives within a timeout period, the sender assumes the frame was lost/corrupted and retransmits it. Simple, but inefficient because the link sits idle during each wait.",
    },
    {
      id: "fc-29",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "Describe Go-Back-N ARQ.",
      back: "In Go-Back-N ARQ, the sender can transmit several frames (up to a window size) without waiting for individual acknowledgments. If a frame is found to be in error/lost, the receiver discards that frame and all subsequent frames, forcing the sender to retransmit that frame and every frame after it, even ones that arrived correctly — simpler but wasteful.",
    },
    {
      id: "fc-30",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "Describe Selective Repeat ARQ.",
      back: "In Selective Repeat ARQ, the sender can also transmit multiple frames within a window, but the receiver individually buffers correctly-received frames even if an earlier frame was lost, and the sender only needs to retransmit the specific frame(s) that were actually lost or corrupted — more efficient than Go-Back-N, but requires more complex buffering at the receiver.",
    },
    {
      id: "fc-31",
      unit: "Unit 3: Data Link Layer",
      tier: "hedge",
      front: "What is HDLC?",
      back: "HDLC (High-level Data Link Control) is a bit-oriented Data Link layer protocol used for both point-to-point and multipoint links, defining frame formats (with flag, address, control, information, and FCS fields) and supporting various modes of operation for reliable data transfer.",
    },
    {
      id: "fc-32",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What is PPP (Point-to-Point Protocol), and what is the PPP Stack?",
      back: "PPP is a widely-used Data Link layer protocol for establishing a direct connection between two nodes, commonly used for dial-up and DSL Internet connections. The PPP Stack includes LCP (Link Control Protocol, to establish/configure/test the link), authentication protocols (PAP/CHAP), and NCPs (Network Control Protocols, to configure the network layer protocol running over the link, e.g. IPCP for IP).",
    },
    {
      id: "fc-33",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What are the three categories of Multiple Access Protocols?",
      back: "Random Access: any station may transmit at any time, with a chance of collision (e.g. ALOHA, CSMA/CD used in Ethernet). Controlled Access: stations coordinate to decide who may transmit next, avoiding collisions (e.g. Reservation, Polling, Token Passing). Channelization: the available bandwidth is divided among stations in advance, using FDMA, TDMA, or CDMA.",
    },
    {
      id: "fc-34",
      unit: "Unit 3: Data Link Layer",
      tier: "hedge",
      front: "Compare Traditional, Fast, and Gigabit Ethernet.",
      back: "Traditional Ethernet (10BASE-T) transmits at 10 Mbps over twisted-pair or coaxial cable. Fast Ethernet (100BASE-T) increases this to 100 Mbps, mainly by refining encoding and using better cabling. Gigabit Ethernet pushes speed further to 1000 Mbps (1 Gbps), while keeping the same basic frame format for backward compatibility.",
    },
    {
      id: "fc-35",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What is IEEE 802.11, and what is Bluetooth?",
      back: "IEEE 802.11 (Wi-Fi) is the standard defining wireless LAN (WLAN) communication, allowing devices to connect to a network without cables using radio waves, typically through an access point. Bluetooth is a short-range wireless technology standard (IEEE 802.15) designed for low-power communication between nearby personal devices (e.g. headphones, keyboards, phones).",
    },
    {
      id: "fc-36",
      unit: "Unit 3: Data Link Layer",
      tier: "hedge",
      front: "Name common Connecting Devices, and what is a Backbone Network?",
      back: "Connecting Devices include Repeaters/Hubs (Physical layer, regenerate/broadcast signals), Bridges/Switches (Data Link layer, forward frames based on MAC address), and Routers (Network layer, forward packets based on IP address). A Backbone Network is a high-capacity central network that interconnects multiple smaller networks or LAN segments together.",
    },
    {
      id: "fc-37",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "What is a Virtual LAN (VLAN)?",
      back: "A VLAN is a logical grouping of devices on one or more physical LANs that are configured (via switch software) to communicate as if they were on the same physical network segment, regardless of their actual physical location — used to improve security, manageability, and to reduce broadcast traffic.",
    },
    {
      id: "fc-38",
      unit: "Unit 3: Data Link Layer",
      tier: "hedge",
      front: "What is Cellular Telephony, and what are Satellite Networks?",
      back: "Cellular Telephony divides a geographic service area into small hexagonal 'cells', each served by its own base station/tower, allowing frequencies to be reused across non-adjacent cells and supporting a much larger number of simultaneous users. Satellite Networks use orbiting satellites (GEO, MEO, or LEO) to relay signals across very large distances, especially useful for remote areas lacking ground infrastructure.",
    },
    {
      id: "fc-39",
      unit: "Unit 3: Data Link Layer",
      tier: "core",
      front: "Distinguish between Virtual Circuit Switching and its relation to Frame Relay and ATM.",
      back: "Virtual Circuit Switching sets up a predefined logical (not physical) path before data transfer begins, and all packets for that session follow the same path, though the physical resources are shared with other connections. Frame Relay and ATM (Asynchronous Transfer Mode) are both virtual-circuit-based WAN technologies — Frame Relay uses variable-length frames, while ATM uses small, fixed-length 53-byte cells for predictable, low-latency switching.",
    },

    // Unit 4: Network Layer
    {
      id: "fc-40",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is an Internetwork, and what is the main job of the Network Layer?",
      back: "An Internetwork (internet) is formed by connecting two or more individual networks together via routers, so devices on different networks can communicate. The Network Layer's main job is to move packets from their source to their final destination across this internetwork, using logical addressing and routing.",
    },
    {
      id: "fc-41",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is Addressing at the Network Layer?",
      back: "Network Layer Addressing (logical/IP addressing) assigns each device a globally unique address (an IP address) that identifies both the network it belongs to and the specific host within that network, allowing routers to determine the correct path to forward a packet toward its destination.",
    },
    {
      id: "fc-42",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is Routing?",
      back: "Routing is the process by which a router determines the best path for forwarding a packet toward its destination network, based on information in a routing table that is built either manually (static routing) or automatically via routing protocols (dynamic routing).",
    },
    {
      id: "fc-43",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is ARP (Address Resolution Protocol)?",
      back: "ARP is a protocol used to map a known logical IP address to its corresponding physical MAC (hardware) address on a local network, since a device needs the destination's MAC address to actually deliver a frame at the Data Link layer.",
    },
    {
      id: "fc-44",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is IP (Internet Protocol)?",
      back: "IP is the core Network Layer protocol responsible for addressing and routing packets (called datagrams) across an internetwork. It is a connectionless, best-effort (unreliable) protocol — it does not guarantee delivery, ordering, or error correction, leaving that to higher layers if needed.",
    },
    {
      id: "fc-45",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is ICMP (Internet Control Message Protocol)?",
      back: "ICMP is a companion protocol to IP used to report errors and send control/diagnostic messages, such as when a destination is unreachable or a packet's Time-To-Live expires. It is the protocol underlying tools like ping and traceroute.",
    },
    {
      id: "fc-46",
      unit: "Unit 4: Network Layer",
      tier: "core",
      front: "What is IPv6, and why was it introduced?",
      back: "IPv6 is the newer version of the Internet Protocol, using 128-bit addresses (versus IPv4's 32-bit addresses), introduced primarily to solve IPv4 address exhaustion given the huge growth in Internet-connected devices. It also improves header format efficiency and built-in support for security (IPsec).",
    },
    {
      id: "fc-47",
      unit: "Unit 4: Network Layer",
      tier: "hedge",
      front: "What is Unicast Routing, and name a Unicast Routing Protocol.",
      back: "Unicast Routing finds the best path for delivering a packet from one single source to one single specific destination. Common Unicast Routing Protocols include RIP (Routing Information Protocol, distance-vector based) and OSPF (Open Shortest Path First, link-state based).",
    },
    {
      id: "fc-48",
      unit: "Unit 4: Network Layer",
      tier: "hedge",
      front: "What is Multicast Routing, and name a Multicast Routing Protocol.",
      back: "Multicast Routing delivers a single packet from one source to a specific group of interested destinations simultaneously (not all hosts, and not just one), efficiently replicating the packet only where the network actually branches toward group members. An example Multicast Routing Protocol is PIM (Protocol Independent Multicast).",
    },

    // Unit 5: Transport Layer
    {
      id: "fc-49",
      unit: "Unit 5: Transport Layer",
      tier: "core",
      front: "What is Process-to-Process Delivery, and how does the Transport Layer achieve it?",
      back: "Process-to-Process Delivery means getting an entire message from a specific application/process on the source machine to the corresponding specific application/process on the destination machine (not just machine-to-machine, which is the Network layer's job). The Transport Layer achieves this using port numbers, which identify the specific process at each end.",
    },
    {
      id: "fc-50",
      unit: "Unit 5: Transport Layer",
      tier: "core",
      front: "What is UDP (User Datagram Protocol)?",
      back: "UDP is a connectionless, unreliable Transport Layer protocol that sends independent datagrams with minimal overhead and no guarantee of delivery, ordering, or duplicate protection. It is used where speed matters more than reliability, e.g. live video/audio streaming, DNS queries.",
    },
    {
      id: "fc-51",
      unit: "Unit 5: Transport Layer",
      tier: "core",
      front: "What is TCP (Transmission Control Protocol)?",
      back: "TCP is a connection-oriented, reliable Transport Layer protocol that establishes a connection (via a three-way handshake) before sending data, guarantees in-order delivery, detects and retransmits lost/corrupted segments, and provides flow and congestion control. It is used where reliability matters, e.g. web browsing, email, file transfer.",
    },
    {
      id: "fc-52",
      unit: "Unit 5: Transport Layer",
      tier: "hedge",
      front: "What is Data Traffic, in the context of Congestion?",
      back: "Data Traffic refers to the pattern and volume of data flowing through a network at a given time. It is a key factor in Congestion, since traffic that is bursty (arrives in large, irregular spikes) is much more likely to overload network resources than traffic that arrives at a smooth, steady rate.",
    },
    {
      id: "fc-53",
      unit: "Unit 5: Transport Layer",
      tier: "core",
      front: "What is Congestion, and what is Congestion Control?",
      back: "Congestion occurs when the amount of data being sent into a network exceeds the capacity that the network (routers, links) can handle, causing packets to be delayed or dropped. Congestion Control refers to the mechanisms (e.g. TCP's slow start, congestion avoidance) used to detect and reduce network load before/after congestion occurs, keeping the network usable.",
    },
    {
      id: "fc-54",
      unit: "Unit 5: Transport Layer",
      tier: "core",
      front: "What is Quality of Service (QoS)?",
      back: "QoS is a set of techniques used to manage and guarantee network performance characteristics (bandwidth, delay, jitter, and reliability) for specific types of traffic, so that time-sensitive applications like voice/video calls receive the priority treatment they need over less time-sensitive traffic like file downloads.",
    },
    {
      id: "fc-55",
      unit: "Unit 5: Transport Layer",
      tier: "hedge",
      front: "Name techniques used to improve QoS.",
      back: "Scheduling (e.g. FIFO queuing, priority queuing, weighted fair queuing) decides the order packets are sent. Traffic Shaping (e.g. leaky bucket, token bucket) regulates the rate/burstiness of outgoing traffic. Resource Reservation reserves buffer space and bandwidth in advance for a flow. Admission Control checks if a new flow can be accepted without degrading existing guaranteed flows.",
    },
    {
      id: "fc-56",
      unit: "Unit 5: Transport Layer",
      tier: "hedge",
      front: "Distinguish between Integrated Services and Differentiated Services (QoS models).",
      back: "Integrated Services (IntServ) provides QoS on a per-flow basis, requiring each individual flow to explicitly reserve resources end-to-end (e.g. via RSVP) before sending data — precise, but doesn't scale well to huge numbers of flows. Differentiated Services (DiffServ) instead classifies traffic into a small number of priority classes and applies per-class treatment at each router — simpler and more scalable, though less precise per flow.",
    },

    // Unit 6: Application Layer
    {
      id: "fc-57",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is the Client-Server Model?",
      back: "The Client-Server Model is an application architecture where a client process initiates a request for a service, and a server process (usually always running and listening) responds by providing that service, e.g. a web browser (client) requesting a page from a web server.",
    },
    {
      id: "fc-58",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is a Socket Interface?",
      back: "A Socket is an endpoint for network communication, identified by the combination of an IP address and a port number. The Socket Interface is the programming API (e.g. Berkeley sockets) that applications use to create, connect, send, and receive data through these endpoints, without needing to manage the underlying protocol details directly.",
    },
    {
      id: "fc-59",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is Name Space, and what is Domain Name Space?",
      back: "A Name Space is the set of all possible names assigned to entities on a network, structured so each name is unique. The Domain Name Space is specifically a hierarchical, tree-structured name space used for the Internet, where each node represents a domain (e.g. com, example.com, www.example.com).",
    },
    {
      id: "fc-60",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is DNS (Domain Name System), and how does Resolution work?",
      back: "DNS is a distributed, hierarchical naming system that translates human-readable domain names (e.g. www.example.com) into numeric IP addresses that computers use to route traffic. Resolution is the process a client (resolver) follows to look up this mapping, usually starting with a local DNS server and, if needed, querying up through root, TLD, and authoritative name servers.",
    },
    {
      id: "fc-61",
      unit: "Unit 6: Application Layer",
      tier: "hedge",
      front: "What are DNS Messages, and what is DDNS?",
      back: "DNS Messages are the query and response messages exchanged between a client/resolver and DNS servers to perform name resolution, typically carried over UDP. DDNS (Dynamic DNS) automatically updates a DNS server's records in real time when a host's IP address changes, useful for devices with non-static (dynamic) IP addresses.",
    },
    {
      id: "fc-62",
      unit: "Unit 6: Application Layer",
      tier: "hedge",
      front: "What is Encapsulation in the context of application data flow?",
      back: "Encapsulation is the process by which each protocol layer wraps the data it receives from the layer above with its own header (and sometimes trailer) information as it moves down the protocol stack for transmission, and unwraps (decapsulates) it symmetrically as it moves back up the stack at the receiver.",
    },
    {
      id: "fc-63",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What protocols handle Electronic Mail and File Transfer?",
      back: "Electronic Mail uses SMTP (Simple Mail Transfer Protocol) to send mail between servers, and POP3 or IMAP for a client to retrieve mail from a mail server. File Transfer commonly uses FTP (File Transfer Protocol), which uses two separate connections — one for control commands and one for the actual data transfer.",
    },
    {
      id: "fc-64",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is HTTP, and what is the World Wide Web (WWW)?",
      back: "HTTP (HyperText Transfer Protocol) is the Application layer protocol that governs how web browsers (clients) and web servers exchange requests and responses to retrieve web content. The World Wide Web (WWW) is the vast, interconnected system of hyperlinked documents/resources (identified by URLs) accessible over the Internet using HTTP.",
    },
    {
      id: "fc-65",
      unit: "Unit 6: Application Layer",
      tier: "hedge",
      front: "What is meant by Digitizing Audio and Video, and Audio/Video Compression?",
      back: "Digitizing Audio and Video is the process of sampling and encoding continuous analog audio/video signals into a digital bit stream so they can be stored/transmitted by computers. Compression (e.g. MP3 for audio, MPEG/H.264 for video) then reduces the size of this digital data by removing redundant or perceptually less-important information, making storage and transmission far more efficient.",
    },
    {
      id: "fc-66",
      unit: "Unit 6: Application Layer",
      tier: "hedge",
      front: "Distinguish between Streaming Stored Audio/Video and Streaming Live Audio/Video.",
      back: "Streaming Stored Audio/Video delivers a pre-recorded file to the user, who can typically pause, rewind, or fast-forward it (e.g. an on-demand video service). Streaming Live Audio/Video delivers a broadcast in real time as it is being captured/generated, with no ability to rewind past what has already streamed (e.g. a live sports broadcast).",
    },
    {
      id: "fc-67",
      unit: "Unit 6: Application Layer",
      tier: "core",
      front: "What is Real-Time Interactive Audio/Video, and what is Voice over IP (VoIP)?",
      back: "Real-Time Interactive Audio/Video refers to communication where all parties send and receive audio/video simultaneously with very low tolerable delay (e.g. a video call), unlike one-way streaming. Voice over IP (VoIP) is the specific technology that enables voice conversations to be carried as digital data packets over an IP network instead of traditional circuit-switched telephone lines.",
    },

    // Unit 7: Switching
    {
      id: "fc-68",
      unit: "Unit 7: Switching",
      tier: "core",
      front: "What is Switching, and name its three fundamental methods.",
      back: "Switching is the technique used to establish a path (and move data along it) between a sender and receiver through a network of interconnected intermediate switching nodes, rather than requiring a direct link between every possible pair of devices. Its three fundamental methods are Circuit Switching, Packet Switching, and Message Switching.",
    },
    {
      id: "fc-69",
      unit: "Unit 7: Switching",
      tier: "core",
      front: "Explain the concept of a Circuit Switching Network.",
      back: "A Circuit Switching Network establishes a single dedicated communication path (circuit) between two end devices for the full duration of a session, going through three phases: Setup (the path is reserved end-to-end), Data Transfer (data flows over the fixed path), and Teardown (the path is released once communication ends). The traditional telephone network is the classic example.",
    },
    {
      id: "fc-70",
      unit: "Unit 7: Switching",
      tier: "hedge",
      front: "What is Control Signaling in a Circuit Switched Network?",
      back: "Control Signaling refers to the exchange of control messages (separate from the actual user data) needed to set up, maintain, and tear down a circuit-switched connection — for example, the signaling used to dial a number, ring the destination phone, and establish the voice path.",
    },
    {
      id: "fc-71",
      unit: "Unit 7: Switching",
      tier: "hedge",
      front: "What is Softswitch Architecture?",
      back: "Softswitch Architecture separates the call control/signaling function (handled in software, the 'softswitch') from the actual media/data transport function (handled by separate gateway hardware), unlike traditional telephone switches which combine both in one dedicated piece of hardware. This separation makes modern VoIP-based telephone networks far more flexible and easier to upgrade.",
    },
    {
      id: "fc-72",
      unit: "Unit 7: Switching",
      tier: "core",
      front: "Explain the concept of Packet Switching, and what is Packet Size?",
      back: "Packet Switching breaks a message into smaller units called packets, each carrying its own header with source/destination addressing, and routes each packet independently through the network — packets may take different paths and can be reassembled at the destination. Packet Size is the length of these units; smaller packets reduce per-packet delay and allow better sharing of link capacity, but add more total header overhead.",
    },
    {
      id: "fc-73",
      unit: "Unit 7: Switching",
      tier: "hedge",
      front: "What are X.25, Frame Relay, and ATM (as packet-switched WAN technologies)?",
      back: "X.25 is an older packet-switching standard that performs extensive error checking at every intermediate node, making it reliable but slow by modern standards. Frame Relay is a faster, simplified successor that assumes a more reliable underlying network and skips most per-hop error correction, using variable-length frames. ATM (Asynchronous Transfer Mode) uses small, fixed-length 53-byte cells to achieve very predictable, low-latency switching suitable for mixed voice/video/data traffic.",
    },
    {
      id: "fc-74",
      unit: "Unit 7: Switching",
      tier: "core",
      front: "Explain the concept of Message Switching.",
      back: "In Message Switching, an entire message (not split into packets) is sent as one whole unit from one intermediate switching node to the next, where it is completely received, stored, and then forwarded on to the next node when the outgoing link is free (a 'store-and-forward' technique). It has largely been replaced by packet switching, since packet switching allows large messages to be broken up for more efficient, parallel use of network links.",
    },
  ],

  cheatSheet: {
    gradingNote:
      "This subject follows Purbanchal University's standard grading: elaborate every answer with a definition, real-world examples, and a clear comparison/diagram-style explanation where the question asks to 'compare' or 'differentiate' — a bare list of terms without explanation loses marks.",
    sections: [],
  },

  diagrams: [],

  mockPaper: {
    title: "Data Communication and Networks — Mock Paper (coming soon)",
    instructions:
      "This mock paper will be added once real past papers for Data Communication and Networks are available, so questions and mark structure match the actual Purbanchal University exam format.",
    questions: [],
  },

  pastPapers: {
    years: [],
    questions: [],
  },

  glossary: [
    { term: "Node", definition: "Any device (computer, printer, router, etc.) connected to and identifiable on a network." },
    { term: "Bandwidth", definition: "The maximum data transfer rate a communication link or network can support, usually measured in bits per second (bps)." },
    { term: "Throughput", definition: "The actual amount of data successfully transferred over a network in a given time, which may be lower than the theoretical bandwidth." },
    { term: "Latency (Delay)", definition: "The total time it takes for a complete message to travel from sender to receiver." },
    { term: "LAN", definition: "Local Area Network — a network usually confined to a single building or campus, under one organization's administration." },
    { term: "WAN", definition: "Wide Area Network — a network that spans a large geographical area, often connecting multiple LANs across cities or countries." },
    { term: "ISP", definition: "Internet Service Provider — an organization that provides individuals and organizations access to the Internet." },
    { term: "Router", definition: "A networking device that forwards data packets between different networks based on their destination address." },
    { term: "Protocol Stack", definition: "The complete set of layered protocols (e.g. TCP/IP suite) that work together to provide network communication." },
  ],

  syllabus: {
    units: [
      {
        unit: "Unit 1: Overview of Data Communication and Networking",
        topics: [
          "Data Communications",
          "Networks",
          "The Internet",
          "Protocols and Standards",
          "Layered Tasks",
          "OSI Model",
          "TCP/IP Protocol Architecture",
        ],
        notes: unit1Notes,
      },
      {
        unit: "Unit 2: Physical Layer",
        topics: [
          "Analog and Digital, Analog Signals, Digital Signals, Analog versus Digital",
          "Data Rate Limit",
          "Transmission Impairments",
          "Line Coding, Block Coding, Sampling",
          "Transmission Mode",
          "Modulation of Digital Data",
          "Modulation of Analog Signal",
          "FDM, WDM, TDM",
          "Guided Media, Unguided Media",
          "Circuit Switching, Telephone Networks",
          "DSL Technology, Cable Modem, SONET",
        ],
        notes: unit2Notes,
      },
      {
        unit: "Unit 3: Data Link Layer",
        topics: [
          "Types of Errors, Detection, Error Correction",
          "Flow and Error Control",
          "Stop and Wait ARQ, Go-Back-N ARQ, Selective Repeat ARQ",
          "HDLC, Point to Point Protocol (PPP)",
          "PPP Stack",
          "Random Access, Controlled Access, Channelization",
          "Traditional Ethernet, Fast Ethernet, Gigabit Ethernet",
          "IEEE 802.11, Bluetooth",
          "Connecting Devices, Backbone Network",
          "Virtual LAN",
          "Cellular Telephony",
          "Satellite Networks",
          "Virtual Circuit Switching",
          "Frame Relay, ATM",
        ],
        notes: unit3Notes,
      },
      {
        unit: "Unit 4: Network Layer",
        topics: [
          "Internetworks",
          "Addressing",
          "Routing",
          "ARP, IP, ICMP, IPv6",
          "Unicast Routing, Unicast Routing Protocol",
          "Multicast Routing, Multicast Routing Protocols",
        ],
        notes: unit4Notes,
      },
      {
        unit: "Unit 5: Transport Layer",
        topics: [
          "Process to Process Delivery",
          "User Datagram Protocol (UDP)",
          "Transmission Control Protocol (TCP)",
          "Data Traffic",
          "Congestion, Congestion Control",
          "Quality of Service (QoS)",
          "Techniques to Improve QoS",
          "Integrated Services, Differentiated Services",
          "QoS in Switched Networks",
        ],
        notes: unit5Notes,
      },
      {
        unit: "Unit 6: Application Layer",
        topics: [
          "Client Server Model",
          "Socket Interface",
          "Name Space, Domain Name Space",
          "Distribution of Name Space, DNS in the Internet",
          "Resolution, DNS Messages, DDNS",
          "Encapsulation",
          "Electronic Mail, File Transfer",
          "HTTP, World Wide Web (WWW)",
          "Digitizing Audio and Video",
          "Audio and Video Compression",
          "Streaming Stored Audio/Video",
          "Streaming Live Audio/Video",
          "Real Time Interactive Audio/Video, Voice over IP",
        ],
        notes: unit6Notes,
      },
      {
        unit: "Unit 7: Switching",
        topics: [
          "Circuit Switching Networks, Concepts",
          "Control Signaling",
          "Soft Switch Architecture",
          "Packet Switching, Packet Size",
          "X.25, Frame Relay, ATM",
          "Message Switching",
        ],
        notes: unit7Notes,
      },
    ],
  },
};
