import type { SubjectContent } from "@/content/types";
import { unit1Notes } from "./notes/unit-1";
import { unit2Notes } from "./notes/unit-2";
import { unit3Notes } from "./notes/unit-3";
import { unit4Notes } from "./notes/unit-4";
import { unit5Notes } from "./notes/unit-5";
import { unit6Notes } from "./notes/unit-6";
import { unit7Notes } from "./notes/unit-7";
import { unit8Notes } from "./notes/unit-8";

export const digitalSystemContent: SubjectContent = {
  flashcards: [
    // Unit 1: Introduction
    {
      id: "fc-1",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "What is the difference between Analog and Digital systems?",
      back: "An Analog system processes continuous signals that can take any value over a range (e.g. a thermometer, a sine wave), while a Digital system processes discrete signals restricted to a finite set of values, almost always just two levels (0 and 1, i.e. binary), making digital circuits more noise-resistant and easier to store/reproduce exactly.",
    },
    {
      id: "fc-2",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "What is a Number System? Name the four common ones used in digital systems.",
      back: "A Number System is a way of representing numbers using a set of symbols and rules. The four common systems are Binary (base 2, digits 0-1), Octal (base 8, digits 0-7), Decimal (base 10, digits 0-9), and Hexadecimal (base 16, digits 0-9 and A-F).",
    },
    {
      id: "fc-3",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "How do you convert Decimal to Binary?",
      back: "Repeatedly divide the decimal number by 2, recording the remainder (0 or 1) at each step, until the quotient becomes 0. The binary equivalent is the sequence of remainders read from last to first (bottom to top).",
    },
    {
      id: "fc-4",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "How do you convert Binary to Decimal?",
      back: "Multiply each binary digit by 2 raised to the power of its position (counting from 0 on the right), then sum all the results. Example: 1011₂ = 1×2³ + 0×2² + 1×2¹ + 1×2⁰ = 8+0+2+1 = 11₁₀.",
    },
    {
      id: "fc-5",
      unit: "Unit 1: Introduction",
      tier: "hedge",
      front: "How do you convert Binary to Octal and Binary to Hexadecimal quickly?",
      back: "For Octal, group binary digits into sets of 3 from the right (pad with leading zeros if needed) and convert each group to its octal digit. For Hexadecimal, group into sets of 4 from the right and convert each group to its hex digit.",
    },
    {
      id: "fc-6",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "What is 1's Complement and how is it calculated?",
      back: "The 1's Complement of a binary number is found by inverting every bit — changing every 0 to 1 and every 1 to 0. Example: 1's complement of 1010 is 0101.",
    },
    {
      id: "fc-7",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "What is 2's Complement and how is it calculated?",
      back: "The 2's Complement of a binary number is found by taking its 1's complement and then adding 1 to the result. It is the standard method computers use to represent negative numbers, because subtraction can then be performed using only addition circuitry.",
    },
    {
      id: "fc-8",
      unit: "Unit 1: Introduction",
      tier: "hedge",
      front: "How is subtraction performed using 2's Complement addition?",
      back: "To compute A − B in binary, take the 2's complement of B and add it to A. If a carry is generated out of the most significant bit, discard it and the result is positive; if no carry is generated, the result is negative and is itself in 2's complement form.",
    },
    {
      id: "fc-9",
      unit: "Unit 1: Introduction",
      tier: "core",
      front: "What is BCD (Binary Coded Decimal)?",
      back: "BCD represents each decimal digit (0-9) individually using its own 4-bit binary code, rather than converting the whole number to pure binary. Example: decimal 25 in BCD is 0010 0101 (2 encoded as 0010, 5 encoded as 0101).",
    },
    {
      id: "fc-10",
      unit: "Unit 1: Introduction",
      tier: "hedge",
      front: "What is the Excess-3 code?",
      back: "Excess-3 is a self-complementing BCD variant formed by adding 3 (0011) to the 4-bit binary value of each decimal digit before encoding it. It is used because its 9's complement can be obtained just by inverting every bit.",
    },
    {
      id: "fc-11",
      unit: "Unit 1: Introduction",
      tier: "hedge",
      front: "What is a Gray Code and why is it useful?",
      back: "Gray Code is a binary numeral system where two successive values differ in only one bit position. It is used in rotary encoders and Karnaugh maps because it minimizes the risk of glitches/errors that occur when multiple bits change at once during a transition.",
    },
    {
      id: "fc-12",
      unit: "Unit 1: Introduction",
      tier: "hedge",
      front: "What is ASCII?",
      back: "ASCII (American Standard Code for Information Interchange) is a 7-bit character encoding standard used to represent text (letters, digits, punctuation, and control characters) as numeric binary codes in computers.",
    },

    // Unit 2: Boolean Algebra
    {
      id: "fc-13",
      unit: "Unit 2: Boolean Algebra",
      tier: "core",
      front: "What is Boolean Algebra?",
      back: "Boolean Algebra is a branch of algebra in which the values of variables are restricted to only two states, true/1 or false/0, and the basic operations are AND (·), OR (+), and NOT (complement, '). It is the mathematical foundation used to analyze and design digital logic circuits.",
    },
    {
      id: "fc-14",
      unit: "Unit 2: Boolean Algebra",
      tier: "core",
      front: "State De Morgan's Theorems.",
      back: "De Morgan's first theorem: (A·B)' = A' + B' (the complement of a product equals the sum of the complements). De Morgan's second theorem: (A+B)' = A'·B' (the complement of a sum equals the product of the complements). These let a NAND/NOR circuit be redrawn using only AND/OR/NOT gates.",
    },
    {
      id: "fc-15",
      unit: "Unit 2: Boolean Algebra",
      tier: "core",
      front: "State the Distributive, Absorption, and Idempotent laws of Boolean Algebra.",
      back: "Distributive: A·(B+C) = A·B + A·C. Absorption: A + A·B = A, and A·(A+B) = A. Idempotent: A+A = A, and A·A = A. These identities are used to simplify Boolean expressions algebraically before drawing a circuit.",
    },
    {
      id: "fc-16",
      unit: "Unit 2: Boolean Algebra",
      tier: "hedge",
      front: "What are the Complement and Identity laws in Boolean Algebra?",
      back: "Complement law: A + A' = 1, and A·A' = 0 (a variable OR'd/AND'd with its own complement always gives 1 or 0). Identity law: A + 0 = A, A·1 = A, A + 1 = 1, and A·0 = 0.",
    },
    {
      id: "fc-17",
      unit: "Unit 2: Boolean Algebra",
      tier: "core",
      front: "List the basic logic gates and their Boolean functions.",
      back: "AND gate: Y = A·B (output is 1 only if all inputs are 1). OR gate: Y = A+B (output is 1 if any input is 1). NOT gate: Y = A' (inverts the input). NAND: Y = (A·B)'. NOR: Y = (A+B)'. XOR: Y = A⊕B (output is 1 only if inputs differ). XNOR: Y = (A⊕B)' (output is 1 only if inputs are equal).",
    },
    {
      id: "fc-18",
      unit: "Unit 2: Boolean Algebra",
      tier: "hedge",
      front: "Why are NAND and NOR called 'universal gates'?",
      back: "NAND and NOR are called universal gates because either one, used alone, can be wired together in different combinations to implement any of the other basic gates (AND, OR, NOT) and therefore any Boolean function, without needing any other gate type.",
    },
    {
      id: "fc-19",
      unit: "Unit 2: Boolean Algebra",
      tier: "core",
      front: "What is a Karnaugh Map (K-Map) and why is it used?",
      back: "A Karnaugh Map is a grid-based graphical method for simplifying Boolean expressions by grouping adjacent cells (containing 1s) that differ in only one variable, following Gray Code ordering across rows/columns. It is used because it avoids lengthy algebraic manipulation and quickly yields a minimal Sum-of-Products expression.",
    },
    {
      id: "fc-20",
      unit: "Unit 2: Boolean Algebra",
      tier: "hedge",
      front: "What are the grouping rules when simplifying a K-Map?",
      back: "Group only adjacent 1s in sizes that are powers of 2 (1, 2, 4, 8...); groups may wrap around the edges of the map; always make groups as large as possible to eliminate the most variables; every 1 must be covered by at least one group, and overlapping groups are allowed if it helps minimize the total number of groups (prime implicants).",
    },
    {
      id: "fc-21",
      unit: "Unit 2: Boolean Algebra",
      tier: "hedge",
      front: "What is a minterm and a maxterm?",
      back: "A minterm is a product (AND) term that includes every variable of the function, either in true or complemented form, and equals 1 for exactly one combination of input values (used to build a Sum-of-Products, SOP). A maxterm is the corresponding sum (OR) term that equals 0 for exactly one input combination (used to build a Product-of-Sums, POS).",
    },

    // Unit 3: Combinational Logic
    {
      id: "fc-22",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is Combinational Logic?",
      back: "Combinational logic is a type of digital circuit whose output at any instant depends only on the present combination of inputs, with no memory of past inputs — unlike sequential logic, it has no feedback or internal state (e.g. adders, encoders, decoders, multiplexers).",
    },
    {
      id: "fc-23",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is a Half Adder? Give its Boolean equations.",
      back: "A Half Adder adds two single binary bits (A and B) and produces a Sum and a Carry, but cannot accept a carry-in from a previous stage. Sum = A⊕B (XOR), Carry = A·B (AND).",
    },
    {
      id: "fc-24",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is a Full Adder? Give its Boolean equations.",
      back: "A Full Adder adds three bits — two operand bits (A, B) and a Carry-in (Cin) from a previous stage — producing a Sum and a Carry-out (Cout). Sum = A⊕B⊕Cin. Cout = A·B + Cin·(A⊕B). Full adders are chained together to build multi-bit binary parallel adders.",
    },
    {
      id: "fc-25",
      unit: "Unit 3: Combinational Logic",
      tier: "hedge",
      front: "What is a Binary Parallel Adder?",
      back: "A Binary Parallel Adder is formed by cascading multiple Full Adders, where the Carry-out of each stage feeds into the Carry-in of the next stage, allowing two multi-bit binary numbers to be added simultaneously across all bit positions (also called a ripple-carry adder).",
    },
    {
      id: "fc-26",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is an Encoder?",
      back: "An Encoder is a combinational circuit that converts 2ⁿ input lines (of which only one is active at a time) into an n-bit binary output code representing which input is active. Example: an 8-to-3 encoder converts 8 input lines into a 3-bit binary code.",
    },
    {
      id: "fc-27",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is a Decoder?",
      back: "A Decoder is a combinational circuit that performs the opposite of an encoder — it converts an n-bit binary input code into one of up to 2ⁿ output lines, activating exactly one output line corresponding to the input code. Example: a 3-to-8 decoder converts a 3-bit code into 8 output lines.",
    },
    {
      id: "fc-28",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is a Multiplexer (MUX)?",
      back: "A Multiplexer is a combinational circuit that selects one of several (2ⁿ) input data lines and routes it to a single output line, based on the value of n select lines. It is often called a 'data selector'. Example: a 4-to-1 MUX has 4 data inputs, 2 select lines, and 1 output.",
    },
    {
      id: "fc-29",
      unit: "Unit 3: Combinational Logic",
      tier: "core",
      front: "What is a Demultiplexer (DEMUX)?",
      back: "A Demultiplexer is a combinational circuit that takes a single input data line and routes it to one of several (2ⁿ) output lines, based on the value of n select lines. It is often called a 'data distributor' and performs the opposite function of a multiplexer.",
    },
    {
      id: "fc-30",
      unit: "Unit 3: Combinational Logic",
      tier: "hedge",
      front: "What are the general steps in the design procedure for a combinational circuit?",
      back: "1) State the problem and identify the required inputs and outputs. 2) Derive the truth table relating every input combination to the required output(s). 3) Obtain the simplified Boolean function for each output, using algebraic simplification or K-maps. 4) Draw the resulting logic diagram using the available gates.",
    },

    // Unit 4: Sequential Logic
    {
      id: "fc-31",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is Sequential Logic, and how does it differ from Combinational Logic?",
      back: "Sequential logic is a type of digital circuit whose output depends on both the present inputs AND the past history of inputs (its current internal state), because it contains memory elements (flip-flops) with feedback. Combinational logic, by contrast, has no memory — its output depends only on the current inputs.",
    },
    {
      id: "fc-32",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is a Flip-Flop?",
      back: "A Flip-Flop is a basic 1-bit memory (bistable) circuit that can store either a 0 or a 1 indefinitely, changing its stored state only when triggered by a clock signal. Flip-flops are the fundamental building blocks of registers, counters, and other sequential circuits.",
    },
    {
      id: "fc-33",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "Describe the SR (Set-Reset) Flip-Flop.",
      back: "The SR flip-flop has two inputs, S (Set) and R (Reset). S=1, R=0 sets the output Q to 1; S=0, R=1 resets Q to 0; S=0, R=0 holds the previous state unchanged. The condition S=1, R=1 is invalid/not allowed, since it leads to an undefined/unpredictable output state.",
    },
    {
      id: "fc-34",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "Describe the D (Data/Delay) Flip-Flop.",
      back: "The D flip-flop has a single data input, D, and one clock input. On each active clock edge, the output Q simply takes on whatever value is present at D at that instant (Q(next) = D), eliminating the SR flip-flop's invalid input combination. It is widely used in registers, since it directly stores/delays the input by one clock cycle.",
    },
    {
      id: "fc-35",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "Describe the JK Flip-Flop.",
      back: "The JK flip-flop behaves like an SR flip-flop (J acts like S, K acts like R) for J=0,K=0 (hold), J=1,K=0 (set), and J=0,K=1 (reset), but resolves the invalid case: when J=1 and K=1, the output simply toggles (flips to the opposite of its current state) instead of being undefined.",
    },
    {
      id: "fc-36",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "Describe the T (Toggle) Flip-Flop.",
      back: "The T flip-flop has a single input, T. When T=0, the output Q holds its current state; when T=1, the output Q toggles (switches to the opposite value) on every active clock edge. It is essentially a JK flip-flop with J and K tied together, and is the basic building block of binary counters.",
    },
    {
      id: "fc-37",
      unit: "Unit 4: Sequential Logic",
      tier: "hedge",
      front: "What is the difference between Level Triggering and Edge Triggering in flip-flops?",
      back: "A level-triggered flip-flop responds to its inputs for as long as the clock signal remains at a particular level (high or low), which can cause unwanted multiple changes. An edge-triggered flip-flop responds only at the exact instant the clock transitions (rising edge 0→1, or falling edge 1→0), giving precise, glitch-free timing control.",
    },
    {
      id: "fc-38",
      unit: "Unit 4: Sequential Logic",
      tier: "hedge",
      front: "What is a Flip-Flop Excitation Table?",
      back: "An excitation table shows what input values (S/R, J/K, D, or T) must be applied to a flip-flop in order to produce a specified transition from its present state to a desired next state. It is used in reverse of a normal truth table, and is essential for the sequential circuit design procedure.",
    },
    {
      id: "fc-39",
      unit: "Unit 4: Sequential Logic",
      tier: "hedge",
      front: "What is the difference between a State Table and a State Diagram?",
      back: "A State Table lists, in rows, every present state and input combination alongside the resulting next state and output — a tabular representation. A State Diagram represents the same information graphically as circles (states) connected by directed arrows (labeled with input/output values) showing the transitions between states.",
    },
    {
      id: "fc-40",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is a Register?",
      back: "A Register is a group of flip-flops (commonly 4, 8, 16, or 32) used together to store a group of related bits (a binary word), with all flip-flops sharing a common clock so the whole word is loaded or updated simultaneously.",
    },
    {
      id: "fc-41",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is a Shift Register, and name its four basic types.",
      back: "A Shift Register is a register in which stored bits can be moved (shifted) one position left or right on each clock pulse, typically built from D flip-flops connected in a chain. The four types are: Serial-In Serial-Out (SISO), Serial-In Parallel-Out (SIPO), Parallel-In Serial-Out (PISO), and Parallel-In Parallel-Out (PIPO).",
    },
    {
      id: "fc-42",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is a Ripple Counter, and why is it called that?",
      back: "A Ripple Counter (asynchronous counter) is built by chaining flip-flops so that the output of one flip-flop serves as the clock input to the next. It is called 'ripple' because a change in count has to propagate (ripple) through each flip-flop stage one after another, rather than all stages changing at once, which introduces cumulative propagation delay.",
    },
    {
      id: "fc-43",
      unit: "Unit 4: Sequential Logic",
      tier: "core",
      front: "What is a Synchronous Counter, and how does it differ from a Ripple Counter?",
      back: "A Synchronous Counter applies the same clock signal simultaneously to every flip-flop, so all bits of the count change at exactly the same time, avoiding the ripple counter's cumulative propagation delay. This makes synchronous counters faster and more reliable for high-speed circuits, though they need extra combinational logic to determine each flip-flop's next input.",
    },
    {
      id: "fc-44",
      unit: "Unit 4: Sequential Logic",
      tier: "hedge",
      front: "What is a BCD Counter (Mod-10 counter)?",
      back: "A BCD counter is a synchronous or asynchronous counter that counts from 0000 through 1001 (decimal 0-9) and then resets back to 0000, instead of continuing to the full binary range, so its count directly matches a single BCD decimal digit.",
    },

    // Unit 5: Register Transfer Logic
    {
      id: "fc-45",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "What is Register Transfer Logic / Register Transfer Language (RTL)?",
      back: "Register Transfer Logic describes, using a symbolic notation, the movement of data between registers and the operations performed on that data during the transfer (e.g. R2 ← R1 means the contents of register R1 are transferred into register R2). It provides a precise way to specify a digital system's microoperations.",
    },
    {
      id: "fc-46",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "What is a Microoperation? Name its four categories.",
      back: "A microoperation is an elementary, register-level operation performed during one clock cycle on data stored in one or more registers. The four categories are: Register Transfer (moving data between registers), Arithmetic (add, subtract, increment), Logic (AND, OR, XOR, NOT, bit-by-bit), and Shift (left/right shift of register contents).",
    },
    {
      id: "fc-47",
      unit: "Unit 5: Register Transfer Logic",
      tier: "hedge",
      front: "What is a Conditional Control Statement in register transfer notation?",
      back: "A conditional control statement specifies that a register transfer only happens if a stated condition is true, written as: If (condition) then (R2 ← R1). It is represented using an if-then form rather than an if-then-else, since the alternative is simply 'do nothing'.",
    },
    {
      id: "fc-48",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "How are negative numbers represented in Signed Binary (Fixed-point) form?",
      back: "The leftmost bit is reserved as the sign bit (0 = positive, 1 = negative). The magnitude of a positive number is stored in true binary form, while a negative number's magnitude is stored in 2's complement form, which is the standard representation used in computer arithmetic.",
    },
    {
      id: "fc-49",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "How is signed binary Addition and Subtraction performed using 2's Complement?",
      back: "Addition: add the two signed numbers directly, including their sign bits, and simply discard any carry-out of the sign bit position. Subtraction: take the 2's complement (negate) of the subtrahend, then add it to the minuend using the same addition rule — this means a single adder circuit handles both operations.",
    },
    {
      id: "fc-50",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "What is Overflow in signed binary arithmetic, and how is it detected?",
      back: "Overflow occurs when the result of adding two numbers with the same sign produces a result whose sign is different, meaning the true result is too large to fit in the available number of bits. It is detected when the carry INTO the sign bit differs from the carry OUT of the sign bit.",
    },
    {
      id: "fc-51",
      unit: "Unit 5: Register Transfer Logic",
      tier: "core",
      front: "What is an Instruction Code, and what are its main parts?",
      back: "An Instruction Code is a group of bits that instructs the computer to perform a specific operation. It is generally divided into an Operation Code (Opcode), which specifies the operation to be performed (e.g. ADD, LOAD, STORE), and an Address part, which specifies the memory location or register of the operand(s).",
    },
    {
      id: "fc-52",
      unit: "Unit 5: Register Transfer Logic",
      tier: "hedge",
      front: "What is a Macrooperation?",
      back: "A macrooperation is a higher-level operation (such as an entire instruction, e.g. ADD) that is actually carried out internally as a defined sequence of several elementary microoperations (fetch, decode, read operand, add, store result) executed one per clock cycle.",
    },
    {
      id: "fc-53",
      unit: "Unit 5: Register Transfer Logic",
      tier: "hedge",
      front: "What are the essential components in the design of a simple computer?",
      back: "A simple computer design typically includes: registers (e.g. Accumulator AC, Program Counter PC, Instruction Register IR, Address Register AR), main memory, a bus system connecting these components, an Arithmetic Logic Unit (ALU) for computation, and a control unit that generates the timing/control signals to sequence instruction fetch, decode, and execution.",
    },

    // Unit 6: Processor and Control Logic Design
    {
      id: "fc-54",
      unit: "Unit 6: Processor and Control Logic Design",
      tier: "core",
      front: "What is Bus Organization in Processor Logic Design?",
      back: "Bus Organization is an arrangement where all registers in the processor are connected to a single common set of shared lines (a bus), rather than wiring separate direct paths between every pair of registers. A multiplexer selects which register's data goes onto the bus at any given time, greatly reducing the amount of wiring needed.",
    },
    {
      id: "fc-55",
      unit: "Unit 6: Processor and Control Logic Design",
      tier: "core",
      front: "What is a Control Unit?",
      back: "The Control Unit is the part of the processor responsible for generating the timing and control signals that direct the sequence of microoperations needed to fetch, decode, and execute each instruction, coordinating the activity of all other components (registers, ALU, memory).",
    },
    {
      id: "fc-56",
      unit: "Unit 6: Processor and Control Logic Design",
      tier: "core",
      front: "What is Hard-Wired Control?",
      back: "Hard-Wired Control implements the control unit using a fixed arrangement of combinational logic gates and flip-flops (finite state machine), where the control signal sequence is physically wired into the circuit. It is fast, but difficult to modify or extend once built, since a change requires rewiring the hardware.",
    },
    {
      id: "fc-57",
      unit: "Unit 6: Processor and Control Logic Design",
      tier: "core",
      front: "What is Microprogram Control?",
      back: "Microprogram Control implements the control unit's logic as a sequence of microinstructions stored in a special Control Memory (Control ROM), where each microinstruction specifies the control signals for one microoperation. It is more flexible than hard-wired control, since changing the control logic just means rewriting the stored microprogram.",
    },
    {
      id: "fc-58",
      unit: "Unit 6: Processor and Control Logic Design",
      tier: "hedge",
      front: "Compare Hard-Wired Control and Microprogram Control.",
      back: "Hard-Wired Control: implemented in fixed logic circuitry, faster execution, but complex/inflexible to modify. Microprogram Control: implemented as microinstructions stored in control memory, slower (since it must read memory) but far easier to modify, debug, or extend by simply changing the stored microprogram.",
    },

    // Unit 7: Computer Design
    {
      id: "fc-59",
      unit: "Unit 7: Computer Design",
      tier: "core",
      front: "What is meant by 'System Configuration' in computer design?",
      back: "System Configuration refers to the overall arrangement of a computer's basic hardware components — memory unit, registers (PC, AR, DR, AC, IR), and the common bus connecting them — and how they are interconnected to carry out instruction fetch, decode, and execution.",
    },
    {
      id: "fc-60",
      unit: "Unit 7: Computer Design",
      tier: "core",
      front: "What are the two basic formats of a Computer Instruction?",
      back: "A Memory-Reference Instruction includes an address part that refers to an operand in memory (opcode + address). A Register-Reference or Input-Output instruction, by contrast, does not reference memory — it specifies an operation to be performed directly on registers or I/O devices, using the address bits to encode the specific operation instead.",
    },
    {
      id: "fc-61",
      unit: "Unit 7: Computer Design",
      tier: "core",
      front: "What is Timing and Control in the Instruction Cycle?",
      back: "Timing and Control refers to the sequence of timing signals (generated by a sequence counter, e.g. T0, T1, T2...) that determine, clock cycle by clock cycle, exactly which microoperations occur during the fetch, decode, and execute phases of each instruction.",
    },
    {
      id: "fc-62",
      unit: "Unit 7: Computer Design",
      tier: "core",
      front: "What are the three main phases of Instruction Execution?",
      back: "Fetch: the instruction is read from memory (addressed by the Program Counter) into the Instruction Register, and PC is incremented. Decode: the opcode in the Instruction Register is examined to determine which operation is required. Execute: the control unit generates the microoperations needed to actually carry out that operation.",
    },

    // Unit 8: Microcomputer System Design
    {
      id: "fc-63",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is Microcomputer Organization?",
      back: "Microcomputer Organization describes how a microprocessor (CPU), memory (RAM/ROM), and Input-Output devices are interconnected via address, data, and control buses to form a complete working computer system, along with how instructions flow between these components.",
    },
    {
      id: "fc-64",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is an Addressing Mode?",
      back: "An Addressing Mode is the method by which an instruction specifies the location of the operand it needs to operate on. Common modes include: Immediate (operand is part of the instruction itself), Direct (address of operand given directly), Indirect (instruction gives the address of a location that itself holds the operand's address), and Register (operand is in a specified register).",
    },
    {
      id: "fc-65",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is a Stack, in the context of a microprocessor system?",
      back: "A Stack is a reserved area of memory (or dedicated registers) that operates on a Last-In-First-Out (LIFO) basis, accessed via a Stack Pointer (SP) register. It is used to temporarily save the return address and register values when a subroutine or interrupt is called, so execution can resume correctly afterward.",
    },
    {
      id: "fc-66",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is a Subroutine, and what are CALL/RETURN instructions?",
      back: "A Subroutine is a reusable, self-contained block of instructions that can be invoked (called) from multiple places in a program. A CALL instruction saves the current Program Counter onto the stack and jumps to the subroutine's address; a RETURN instruction pops that saved address back off the stack into the Program Counter, resuming execution right after the original CALL.",
    },
    {
      id: "fc-67",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is an Interrupt?",
      back: "An Interrupt is a signal (from hardware or software) that temporarily suspends the CPU's normal instruction sequence so it can service a more urgent event (e.g. a key press, a completed I/O transfer). The CPU saves its current state (Program Counter and registers) onto the stack, executes an Interrupt Service Routine (ISR), and then restores its state to resume the original program.",
    },
    {
      id: "fc-68",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is an Input-Output (I/O) Interface?",
      back: "An I/O Interface is the hardware circuitry that sits between the CPU/system bus and an external I/O device, handling the differences in speed, data format, and operating mode between the fast CPU and the (usually much slower) peripheral device.",
    },
    {
      id: "fc-69",
      unit: "Unit 8: Microcomputer System Design",
      tier: "hedge",
      front: "What are the common I/O data transfer techniques?",
      back: "Programmed I/O: the CPU actively polls the device's status and transfers each data item itself, wasting CPU time waiting. Interrupt-driven I/O: the device signals the CPU (via an interrupt) only when it's ready, letting the CPU do other work in the meantime. DMA: dedicated hardware transfers data directly, without CPU involvement per byte/word.",
    },
    {
      id: "fc-70",
      unit: "Unit 8: Microcomputer System Design",
      tier: "core",
      front: "What is Direct Memory Access (DMA)?",
      back: "DMA is a technique that allows an I/O device (via a DMA controller) to transfer data directly to or from main memory without the CPU's continuous involvement, greatly speeding up large data transfers (e.g. disk or network I/O) by removing the CPU as a bottleneck for every single word transferred.",
    },
    {
      id: "fc-71",
      unit: "Unit 8: Microcomputer System Design",
      tier: "hedge",
      front: "What is 'Cycle Stealing' in DMA transfer?",
      back: "Cycle Stealing is a DMA mode in which the DMA controller temporarily takes control of the system bus for just one memory cycle at a time to transfer a single word, then releases the bus back to the CPU — allowing DMA transfer to proceed while still letting the CPU continue executing most of its own instructions.",
    },
  ],

  cheatSheet: {
    gradingNote:
      "This subject follows Purbanchal University's standard grading: elaborate every answer with a definition, a worked example, and (for numeric conversions) a step-by-step calculation ending in the final answer — a bare formula or bare final number without the working steps loses marks.",
    sections: [],
  },

  diagrams: [],

  mockPaper: {
    title: "Digital System — Mock Paper (coming soon)",
    instructions:
      "This mock paper will be added once real past papers for Digital System are available, so questions and mark structure match the actual Purbanchal University exam format.",
    questions: [],
  },

  pastPapers: {
    years: [],
    questions: [],
  },

  glossary: [
    { term: "Bit", definition: "A single binary digit, either 0 or 1; the smallest unit of digital information." },
    { term: "Nibble", definition: "A group of 4 bits, equal to half a byte." },
    { term: "Byte", definition: "A group of 8 bits, the standard unit for addressing memory." },
    { term: "Radix / Base", definition: "The number of unique digits (including zero) used in a positional number system, e.g. 2 for binary, 10 for decimal." },
    { term: "MSB", definition: "Most Significant Bit — the bit in a binary number with the highest positional value (leftmost bit)." },
    { term: "LSB", definition: "Least Significant Bit — the bit in a binary number with the lowest positional value (rightmost bit)." },
    { term: "Overflow", definition: "An error condition where the result of an arithmetic operation exceeds the number of bits available to represent it." },
    { term: "Self-complementing code", definition: "A code (like Excess-3) whose 9's complement can be obtained by simply inverting each bit of the code." },
    { term: "Weighted code", definition: "A code (like BCD) in which each bit position carries a fixed positional weight used to derive the represented value." },
  ],

  syllabus: {
    units: [
      {
        unit: "Unit 1: Introduction",
        topics: [
          "Introduction to Analog and Digital Systems",
          "Number Systems (Binary, Octal, Decimal, Hexadecimal)",
          "Number Base Conversion",
          "1's and 2's Complements",
          "Subtraction using 1's and 2's Complements",
          "Binary Codes (BCD, Excess-3, Gray Code, ASCII codes)",
        ],
        notes: unit1Notes,
      },
      {
        unit: "Unit 2: Boolean Algebra",
        topics: [
          "Basic Definitions",
          "Basic Theorems and Properties of Boolean Algebra",
          "Boolean Functions",
          "Digital Logic Gates (Name, Graphic Symbol, Algebraic Function, Truth Table)",
          "Simplification of Boolean Functions using K-Map Method (two and three variable maps)",
        ],
        notes: unit2Notes,
      },
      {
        unit: "Unit 3: Combinational Logic",
        topics: [
          "Introduction to Combinational Logic",
          "Design Procedure",
          "Adders",
          "Binary Parallel Adder",
          "Encoders",
          "Decoders",
          "Multiplexers",
          "Demultiplexers",
        ],
        notes: unit3Notes,
      },
      {
        unit: "Unit 4: Sequential Logic",
        topics: [
          "Introduction to Sequential Logic",
          "Flip-Flops (Basic, RS, D, JK, T)",
          "Triggering of Flip-Flops",
          "Flip-Flop Excitation Tables",
          "Analysis of Sequential Circuits (State Table, State Diagram, State Equations, Flip-Flop Input Functions)",
          "Design Procedure",
          "Registers (4-bit register)",
          "Shift Registers",
          "Ripple Counters",
          "Synchronous Counters (Binary and BCD counter)",
        ],
        notes: unit4Notes,
      },
      {
        unit: "Unit 5: Register Transfer Logic",
        topics: [
          "Introduction to Register Transfer Logic",
          "Inter-register Transfer",
          "Arithmetic, Logic and Shift Micro-operations",
          "Conditional Control Statements",
          "Fixed-point Binary Data (Signed Binary Numbers)",
          "Arithmetic Addition and Subtraction",
          "Overflow",
          "Instruction Codes",
          "Macrooperations",
          "Design of a Simple Computer",
        ],
        notes: unit5Notes,
      },
      {
        unit: "Unit 6: Processor and Control Logic Design",
        topics: [
          "Introduction to Processor Logic Design",
          "Processor Organization (Bus Organization only)",
          "Introduction to Control Logic Design",
          "Microprogram Control and Hard-Wired Control (Definitions, Block Diagram, Comparison and Differences)",
        ],
        notes: unit6Notes,
      },
      {
        unit: "Unit 7: Computer Design",
        topics: [
          "Introduction to Computer Design",
          "System Configuration",
          "Computer Instructions",
          "Timing and Control",
          "Execution of Instructions",
        ],
        notes: unit7Notes,
      },
      {
        unit: "Unit 8: Microcomputer System Design",
        topics: [
          "Introduction",
          "Microcomputer Organization",
          "Instructions (Basic Sets of Microprocessor Instructions) and Addressing Modes",
          "Stack, Subroutines and Interrupt",
          "Input-Output Interface",
          "Direct Memory Access",
        ],
        notes: unit8Notes,
      },
    ],
  },
};
